### ISSUE TITLE
Face paint removed upon loading actor

### ISSUE THREAD

**Issue by Ghoulishlycool** [mdotstrange/NightmarePuppeteerPublic#128] opened 2020-08-25 17:32 UTC
Whenever an actor is loaded, all face paint is removed.

**Comment by mdotstrange** [comment] 2020-08-25 22:09
Can you describe the steps to reproduce this? Thanks

**Comment by Ghoulishlycool** [comment] 2020-08-26 07:16
Choose an actor head that does not support mask texture, paint it up, save then load.
The paint is gone, but it's stored within the paint editor so simply opening the paint tool again and closing it will re apply the face paint.

**Comment by mdotstrange** [comment] 2020-08-26 07:57
Thanks for explanation- so right now that is the intended behavior- how would you like it to work? The painted head loads when you load the actor- So you don't have to return to the Paint head menu?

**Comment by mdotstrange** [comment] 2020-08-26 09:22
I initially misunderstood you- you mean saving and loading from the 12 slots on the edit actor menu eh? I thought you meant when you quit and restart NP as I just fixed that- I'll have a look at the slots now

**Comment by mdotstrange** [comment] 2020-08-26 09:36
Just fixed the saving/loading as well- I'll upload a new build with it tomorrow-

**Comment by mdotstrange** [comment] 2020-08-27 00:39
New build on Steam that addresses this- can you test it and let me know if it works as  you expect it to? Thanks!

**Comment by Ghoulishlycool** [comment] 2020-08-27 03:10
Apologies for the vagueness, I've just tested this, and it works just fine now.

**Comment by mdotstrange** [comment] 2020-08-27 04:35
Ok great thanks- closing this

**Closed by mdotstrange** 2020-08-27 04:35 UTC
