### ISSUE TITLE
Some heads glitch in To Tha Moon

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#170] opened 2020-09-05 04:31 UTC
A weight painting issue? Disconnected vertices? Unweighted remnants from head separation process?

Blame the moon? Neighboring scenes Basement and Night Rouser aren't affected.

The affected models are many, but quite easy to spot with R+1, so I'm not going to screenshot all of them:

https://imgur.com/a/SNHTxq0

**Comment by tonikone** [comment] 2020-09-05 04:41
...Presenting scene seems to be affected. There the glitch moves to the character right, and is less pronounced.

**Comment by tonikone** [comment] 2020-09-05 04:44
Rotating reveals the direction of the glitch is stationary.

**Comment by tonikone** [comment] 2020-09-05 04:51
Jail seems to affected a bit.

**Comment by tonikone** [comment] 2020-09-05 04:58
Policey seems to be affected.

**Comment by tonikone** [comment] 2020-09-05 05:04
House on fire is a bit affected. The glitches appear on particular models, so I'm pausing the hunt in scenes here.

**Comment by mdotstrange** [comment] 2020-09-05 06:27
What a weird one 0_0 Looking into this

**Comment by mdotstrange** [comment] 2020-09-05 06:42
Doing some testing- a particular model will have the bug in the Moon scene then not show it in others- can't find the cause so far- really weird bug-

**Comment by mdotstrange** [comment] 2020-09-05 06:57
Has something to do with a floating point issue- Actors are far from 0,0,0 in Tha Moon scene

**Comment by mdotstrange** [comment] 2020-09-05 07:14
Seems a combination of a floating point error and a skinning issue on the models-

**Comment by mdotstrange** [comment] 2020-09-05 07:41
Ok I know how to fix the affected heads- is that all of them that are affected in your link?

**Comment by mdotstrange** [comment] 2020-09-05 08:01
Seems to be all the MakeHuman made heads

**Comment by mdotstrange** [comment] 2020-09-05 08:30
Good find! Yeh all make human heads- I know how to fix it now- thanks!

**Comment by mdotstrange** [comment] 2020-09-05 09:58
Just uploaded new Build that should fix this

**Comment by mdotstrange** [comment] 2020-09-06 05:00
Fixed in newest build so closing this- thanks!

**Closed by mdotstrange** 2020-09-06 05:00 UTC
