### ISSUE TITLE
Local VLooper actions carry automatically to buddy on actor switch

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#30] opened 2020-08-06 20:51 UTC
Reproduce: The goal is to record Actor1 actions with VLooper1 and Buddy actions with VLooper2. Clear local VLoopers. Record Actor1 action to Vlooper1. Stop recording. Switch to buddy. Buddy starts Actor1 VLooper actions immediately without activating the VLooper2, and Actor1 now does not do things that were recorded to VLooper1. Clearing VLooper2 has no effect, since nothing might be there.

**Comment by mdotstrange** [comment] 2020-08-06 21:46
Will take a look at this- thanks!

**Comment by mdotstrange** [comment] 2020-08-07 08:14
Re-read this and this is the intended behavior from the code- the vloopers are recording/playing back action that effect the current main actor BUT thinking about it this does not make sense to the user as they aren't aware of the main actor(which is whatever is NOT the buddy when the scene starts- I'll see if I can figure out how to make it remember which actor the action shouldn't execute on-

**Comment by mdotstrange** [comment] 2020-08-07 08:30
Switching it over so VLooper 1 only acts on one actor and VLooper2 on the buddy- this makes more sense-

**Comment by tonikone** [comment] 2020-08-07 13:15
> Would you prefer that Vlooper1 only acts on one specific actor(Main) and Vlooper2 only acts on the Buddy actor?

Mixing manipulations of both actors into single Vlooper is good, but I'd like to see a possibility of single actor action switches being contained in single Vlooper (just like you intended ), but without bleeding into other actor on actor switch. There is a lag after switch before unexpected behaviour occurs, wait patiently. Alt+q animation set switching with non-recorded buddy confirms weirdness 100%, if the behaviour isn't apparent in five seconds. 

The order of what goes into what slot does not matter, just possibility of recording and starting single VLooper without it starting to affect other character that was not manipulated.

This is a good feature and needs a gentle intro in the manual to avoid confusion. Lay out the spec and intent in the manual. The lack of visual indicators of VLooper states makes this a feature that will grow on the user only by using it a lot. Did I press the stop recording button before pressing F2 to start? Uh, did I press the F2 to stop playback before record? Is recording on? This mental bookkeeping should be avoided somehow by visual indicators. Oh I so wish there was completely developer programmable LEDs on all keyboards.  Windows should make that a dev feature so the world would follow.

**Comment by mdotstrange** [comment] 2020-08-08 01:43
Oh made it so Looper1 controls actor1 and 2 does 2- I agree about the lack of indicators/status- since what the Puppeteerian sees is what the view sees its difficult to come up with a way to track what they are doing without affecting the final output etc- will think about this

**Comment by mdotstrange** [comment] 2020-08-08 02:13
Added these indicators- displays red record button when recording- green play on play- Actor1 on left- Buddy on right side https://i.imgur.com/XRVmSou.jpg)

**Comment by mdotstrange** [comment] 2020-08-08 02:20
Going with the indicators and separate loopers complete- closing this- thanks!

**Closed by mdotstrange** 2020-08-08 02:20 UTC
Labels: bug
