### ISSUE TITLE
Broken News scene : Many characters have a tendency of getting a leg stuck to RED floor after jump

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#14] opened 2020-08-04 15:34 UTC
The raised platform seems to a safe place to jump. Walking around might clear out the problem if both feet don't get stuck.

**Comment by mdotstrange** [comment] 2020-08-04 21:17
I adjusted and rebuilt the Navmesh but because of the geo the Navmesh in this scene is just nuts 0_0 When I using NP I reset the actors a lot- by design the ragdoll influence is randomized- so stronger the ragdoll, the more likely it is for glitching/borkin- I could disable the random ragdoll and and replace with user sliders- what do you think? It prob won't stop all borking but can help

**Comment by tonikone** [comment] 2020-08-05 13:42
Good grief, I just noticed I've pressed the wrong button combo for actor reset all the time. You might have to ignore parts of issues where reset did not help. Sorry!

Reading the manual is a good solution to this problem.

**Comment by mdotstrange** [comment] 2020-08-07 01:09
I had the same reset issue after I changed the keys- sorry about that- I redid the Navmesh in this set anyway so its better and not blocking the path to the chairs- closing this-

**Closed by mdotstrange** 2020-08-07 01:09 UTC
